#configuración sv
gdr_d1=Opciones de daños relacionados con viento/tornado/agua:
gdr_d2=Habilitar daños relacionados con el agua
gdr_d3=Habilitar daños relacionados con tornados
gdr_d4=Habilitar daños relacionados con el viento
gdr_d5=tvirus Opciones:
gdr_d6=Fuerza de zombi
gdr_d7=NMRIH Zombis
gdr_d8=No juegues con esta configuración a menos que sepas lo que estás haciendo.
gdr_d9=Opciones avanzadas:
gdr_d10=Opción de simulación (Cambiar la calidad de la simulación):
gdr_d11=Calidad de simulación de tornado
gdr_d12=Calidad de simulación de terremotos
gdr_d13=Calidad de simulación de agua
gdr_d14=Calidad de simulación de viento
gdr_d15=Opciones de viento:
gdr_d16=Habilitar viento físico
gdr_d17=Habilitar Viento post-daño sin colisión
gdr_d18=Habilitar el tiempo de espera de la base sin colisión del daño posterior al viento
gdr_d19=Habilitar la extensión del tiempo base sin colisión del viento después del daño
gdr_d20=Habilitar reducción de masa después del daño del viento
gdr_d21=Opciones de Terremoto:
gdr_d22=Habilitar grupo de colisión de cambio de terremoto
gdr_d23=Opciones de Volcán/Luna/Asteroide:
gdr_d24=Habilitar cambio climático de volcán/luna/asteroides (puede causar retraso)
gdr_d25=Aumento de la presión del volcán/deslizamiento
gdr_d26=Disminución de la presión del volcán/deslizamiento
gdr_d27=Opciones de clima:
gdr_d28=Habilitar accesorios de daño de lluvia ácida (puede causar retraso)
gdr_d28.1=Habilitar npcs de daño por lluvia ácida (puede causar retraso)
gdr_d29=Opciones de Agua/Lava e Inundación/Tsunami:
gdr_d30=nivel mínimo de inundación
gdr_d31=nivel máximo de inundación
gdr_d32=Nivel de inicio del tsunami
gdr_d33=Nivel medio del tsunami
gdr_d34=Nivel final del tsunami
gdr_d35=Velocidad del tsunami
gdr_d36=Opciones de tornado:
gdr_d37=Habilitar velocidad de tornado personalizada
gdr_d38=Velocidad de tornado
gdr_d39=Tiempo de vida mínimo del tornado
gdr_d40=Vida máxima de tornado
gdr_d41=Daño de tornado
gdr_d42=Gráficos del servidor principal:
gdr_d43=Habilitar ambiente
gdr_d44=Activar efecto GFX
gdr_d45=Habilitar efecto de niebla
gdr_d46=Opciones de colisión antilag:
gdr_d47=PD NC BT: Tiempo base sin colisión posterior al daño\n\nCPPPS: colisiones por accesorio por segundo\n\nCAPS: promedio de colisiones por segundo
gdr_d48=CPPP máx.
gdr_d49=DP máx NC BT
gdr_d50=Máx. MAYÚSCULAS (s)
gdr_d51=Opciones de Antilag:
gdr_d52=Modo antilag (sin trabajo)
gdr_d53=Activar Antilag
gdr_d54=Opciones de generación automática:
gdr_d55=Tiempo de aparición automática
gdr_d56=Tiempo de eliminación de generación automática
gdr_d57=Probabilidad de aparición automática
gdr_d58=Opciones de caja de generación automática:
gdr_d59=Desactivar mapa Tornados
gdr_d60=Habilitar mensajes de chat
gdr_d61=Habilitar reproducción automática
gdr_d62=Opciones de temperatura corporal:
gdr_d63=Habilitar temperatura corporal
gdr_d64=Habilitar respiración a temperatura corporal
gdr_d65=Habilitar daños relacionados con la temperatura corporal
gdr_d65.1=Habilitar daños relacionados con la temperatura de npcs
gdr_d66=Habilitar cambio de temperatura corporal Velocidad del jugador
gdr_d67=Habilitar cambio de valor de temperatura corporal
gdr_d68=Velocidad de caminata predeterminada del jugador
gdr_d69=Velocidad de sprint predeterminada del jugador
gdr_d70=Opciones de oxígeno corporal:
gdr_d71=Habilitar oxígeno corporal
gdr_d71.1=Habilitar oxígeno de npcs
gdr_d72=Habilitar daños relacionados con el oxígeno corporal
gdr_d73=Habilitar daños relacionados con el oxígeno corporal
gdr_d74=DNC: Ciclo Día y Noche
gdr_d75=Opciones DNC:
gdr_d76=Activar DNC
gdr_d77=DNC en pausa
gdr_d78=DNC en tiempo real
gdr_d79=Habilitar DNC Crear light_environment
gdr_d80=Duración Día
gdr_d81=Duración Noche
gdr_d82=Tamaño de la luna
gdr_d83=Opciones de construcción espacial:
gdr_d84=Activar compatibilidad con Spacebuild
gdr_d85=Opciones de Zorrotormenta:
gdr_d86=Activar compatibilidad con Stormfox
gdr_d87=Habilitar grid de Sistema de calor
gdr_d88=Habilitar Sistema de calor

#configuración cl
gdr_dcl_1=Opciones gráficas avanzadas:
gdr_dcl_2=Calidad del agua
gdr_dcl_3=Calidad del sombreador de agua
gdr_dcl_4=Calidad de lava
gdr_dcl_5=Calidad de la niebla
gdr_dcl_6=Sección dedicada al Radar Doppler.\nUsar con precaución.
gdr_dcl_7=Resolución
gdr_dcl_8=Modo Monocromático
gdr_dcl_9=Distancia máxima de renderizado
gdr_dcl_10=Frecuencia de actualización (Hz)
gdr_dcl_11=Frecuencia de actualización (Hz)
gdr_dcl_12=Opciones de gráficos.
gdr_dcl_13=GP: Partículas terrestres\n\nWP:Partículas meteorológicas\n\nSP: Partículas de pantalla
gdr_dcl_14=Habilitar sobregiro experimental
gdr_dcl_15=Habilitar agitar pantalla
gdr_dcl_16=Habilitar dibujar efectos de caída de techo
gdr_dcl_17=Habilitar PG
gdr_dcl_18=Habilitar WP
gdr_dcl_19=Habilitar SP
gdr_dcl_20=Habilitar SP manual
gdr_dcl_21=SP máx.
gdr_dcl_22=Opciones de pantalla:
gdr_dcl_23=1: pantalla de cuerpo\n\n2: pantalla de presión\n\n3: pantalla de terremoto\n\n4: pantalla de SpaceBuild\n\n5:sistema de calor hud
gdr_dcl_24=Habilitar Hud
gdr_dcl_25=Habilitar efectos de pantalla de temperatura corporal
gdr_dcl_26=Habilitar vómito de temperatura corporal
gdr_dcl_27=Habilitar estornudo de temperatura corporal
gdr_dcl_28=Activar efectos de pantalla bajo el agua
gdr_dcl_29=Activar efectos de pantalla UnderLava
gdr_dcl_30=Tipo de pantalla
gdr_dcl_31=Pantalla de viento Hud
gdr_dcl_32=Visualización de temperatura del Hud
gdr_dcl_33=Opciones de audio:
gdr_dcl_34=Volumen de viento ligero
gdr_dcl_35=Volumen de viento moderado
gdr_dcl_36=Volumen de viento fuerte
gdr_dcl_37=Volumen de onda sonora
gdr_dcl_38=Opciones de audio de Hud:
gdr_dcl_39=hud Volumen de hogar
gdr_dcl_40=hud Volumen de advertencia
gdr_dcl_41=Habilitar dibujar traza de ruta de tornado

#pestañas del menú de herramientas
gdr_dserver=servidor
gdr_dmain=principal
gdr_dadvanced=Avanzado
gdr_dautospawn=Aparición automática
gdr_dnc=DNC

gdr_dserver_hud=Hud del servidor
gdr_daddons=complementos
gdr_dserver_graphics=Gráficos de servidor
gdr_dserver_hud=Hud del servidor
gdr_dvolume=Volumen
gdr_dadvanced_graphics=Gráficos avanzados
gdr_dgraphics=Gráficos
gdr_dhud=Hud
gdr_dheatsystem=Sistema de calor (Beta)


#hud

gdr_dhud_air_temperature=Temperatura del aire: 
gdr_dhud_body_temperature=Temperatura corporal: 
gdr_dhud_body_oxygen=Oxígeno Corporal: 
gdr_dhud_humidity=Humedad: 

gdr_dhud_wind_speed=Velocidad del viento: 
gdr_dhud_local_wind_speed=Velocidad local del viento: 
gdr_dhud_wind_drection=Dirección del viento: 
gdr_dhud_precipitation=Current Precipitation: 
gdr_dhud_wet_bulve_temperature=Temperatura de vulva humeda: 
gdr_dhud_dewpoint=Punto de rocio: 
gdr_dhud_windchill=Wind Chill: 
gdr_dhud_heatindex=Calor Index: 
gdr_dhud_airflow=Fujo de aire: 
gdr_dhud_latentheat=Latent Heat: 
gdr_dhud_clouddensity=Densidad de nubes: 
gdr_dhud_terraintype=Tipo De Terreno: 
gdr_dhud_incomingRadiation=Radiación entrante: 