#configuración sv
gdr_1=Opciones de daños relacionados con viento/tornado/agua:
gdr_2=Habilitar daños relacionados con el agua
gdr_3=Habilitar daños relacionados con tornados
gdr_4=Habilitar daños relacionados con el viento
gdr_5=tvirus Opciones:
gdr_6=Fuerza de zombi
gdr_7=NMRIH Zombis
gdr_8=No juegues con esta configuración a menos que sepas lo que estás haciendo.
gdr_9=Opciones avanzadas:
gdr_10=Opción de simulación (Cambiar la calidad de la simulación):
gdr_11=Calidad de simulación de tornado
gdr_12=Calidad de simulación de terremotos
gdr_13=Calidad de simulación de agua
gdr_14=Calidad de simulación de viento
gdr_15=Opciones de viento:
gdr_16=Habilitar viento físico
gdr_17=Habilitar Viento post-daño sin colisión
gdr_18=Habilitar el tiempo de espera de la base sin colisión del daño posterior al viento
gdr_19=Habilitar la extensión del tiempo base sin colisión del viento después del daño
gdr_20=Habilitar reducción de masa después del daño del viento
gdr_21=Opciones de Terremoto:
gdr_22=Habilitar grupo de colisión de cambio de terremoto
gdr_23=Opciones de Volcán/Luna/Asteroide:
gdr_24=Habilitar cambio climático de volcán/luna/asteroides (puede causar retraso)
gdr_25=Aumento de la presión del volcán/deslizamiento
gdr_26=Disminución de la presión del volcán/deslizamiento
gdr_27=Opciones de clima:
gdr_28=Habilitar accesorios de daño de lluvia ácida (puede causar retraso)
gdr_28.1=Habilitar npcs de daño por lluvia ácida (puede causar retraso)
gdr_29=Opciones de Agua/Lava e Inundación/Tsunami:
gdr_30=nivel mínimo de inundación
gdr_31=nivel máximo de inundación
gdr_32=Nivel de inicio del tsunami
gdr_33=Nivel medio del tsunami
gdr_34=Nivel final del tsunami
gdr_35=Velocidad del tsunami
gdr_36=Opciones de tornado:
gdr_37=Habilitar velocidad de tornado personalizada
gdr_38=Velocidad de tornado
gdr_39=Tiempo de vida mínimo del tornado
gdr_40=Vida máxima de tornado
gdr_41=Daño de tornado
gdr_42=Gráficos del servidor principal:
gdr_43=Habilitar ambiente
gdr_44=Activar efecto GFX
gdr_45=Habilitar efecto de niebla
gdr_46=Opciones de colisión antilag:
gdr_47=PD NC BT: Tiempo base sin colisión posterior al daño\n\nCPPPS: colisiones por accesorio por segundo\n\nCAPS: promedio de colisiones por segundo
gdr_48=CPPP máx.
gdr_49=DP máx NC BT
gdr_50=Máx. MAYÚSCULAS (s)
gdr_51=Opciones de Antilag:
gdr_52=Modo antilag (sin trabajo)
gdr_53=Activar Antilag
gdr_54=Opciones de generación automática:
gdr_55=Tiempo de aparición automática
gdr_56=Tiempo de eliminación de generación automática
gdr_57=Probabilidad de aparición automática
gdr_58=Opciones de caja de generación automática:
gdr_59=Desactivar mapa Tornados
gdr_60=Habilitar mensajes de chat
gdr_61=Habilitar reproducción automática
gdr_62=Opciones de temperatura corporal:
gdr_63=Habilitar temperatura corporal
gdr_64=Habilitar respiración a temperatura corporal
gdr_65=Habilitar daños relacionados con la temperatura corporal
gdr_65.1=Habilitar daños relacionados con la temperatura de npcs
gdr_66=Habilitar cambio de temperatura corporal Velocidad del jugador
gdr_67=Habilitar cambio de valor de temperatura corporal
gdr_68=Velocidad de caminata predeterminada del jugador
gdr_69=Velocidad de sprint predeterminada del jugador
gdr_70=Opciones de oxígeno corporal:
gdr_71=Habilitar oxígeno corporal
gdr_71.1=Habilitar oxígeno de npcs
gdr_72=Habilitar daños relacionados con el oxígeno corporal
gdr_73=Habilitar daños relacionados con el oxígeno corporal
gdr_74=DNC: Ciclo Día y Noche
gdr_75=Opciones DNC:
gdr_76=Activar DNC
gdr_77=DNC en pausa
gdr_78=DNC en tiempo real
gdr_79=Habilitar DNC Crear light_environment
gdr_80=Duración Día
gdr_81=Duración Noche
gdr_82=Tamaño de la luna
gdr_83=Opciones de construcción espacial:
gdr_84=Activar compatibilidad con Spacebuild
gdr_85=Opciones de Zorrotormenta:
gdr_86=Activar compatibilidad con Stormfox
gdr_87=Habilitar grid de Sistema de calor
gdr_88=Habilitar Sistema de calor

#configuración cl
gdr_cl_1=Opciones gráficas avanzadas:
gdr_cl_2=Calidad del agua
gdr_cl_3=Calidad del sombreador de agua
gdr_cl_4=Calidad de lava
gdr_cl_5=Calidad de la niebla
gdr_cl_6=Sección dedicada al Radar Doppler.\nUsar con precaución.
gdr_cl_7=Resolución
gdr_cl_8=Modo Monocromático
gdr_cl_9=Distancia máxima de renderizado
gdr_cl_10=Frecuencia de actualización (Hz)
gdr_cl_11=Frecuencia de actualización (Hz)
gdr_cl_12=Opciones de gráficos.
gdr_cl_13=GP: Partículas terrestres\n\nWP:Partículas meteorológicas\n\nSP: Partículas de pantalla
gdr_cl_14=Habilitar sobregiro experimental
gdr_cl_15=Habilitar agitar pantalla
gdr_cl_16=Habilitar dibujar efectos de caída de techo
gdr_cl_17=Habilitar PG
gdr_cl_18=Habilitar WP
gdr_cl_19=Habilitar SP
gdr_cl_20=Habilitar SP manual
gdr_cl_21=SP máx.
gdr_cl_22=Opciones de pantalla:
gdr_cl_23=1: pantalla de cuerpo\n\n2: pantalla de presión\n\n3: pantalla de terremoto\n\n4: pantalla de SpaceBuild\n\n5:sistema de calor hud
gdr_cl_24=Habilitar Hud
gdr_cl_25=Habilitar efectos de pantalla de temperatura corporal
gdr_cl_26=Habilitar vómito de temperatura corporal
gdr_cl_27=Habilitar estornudo de temperatura corporal
gdr_cl_28=Activar efectos de pantalla bajo el agua
gdr_cl_29=Activar efectos de pantalla UnderLava
gdr_cl_30=Tipo de pantalla
gdr_cl_31=Pantalla de viento Hud
gdr_cl_32=Visualización de temperatura del Hud
gdr_cl_33=Opciones de audio:
gdr_cl_34=Volumen de viento ligero
gdr_cl_35=Volumen de viento moderado
gdr_cl_36=Volumen de viento fuerte
gdr_cl_37=Volumen de onda sonora
gdr_cl_38=Opciones de audio de Hud:
gdr_cl_39=hud Volumen de hogar
gdr_cl_40=hud Volumen de advertencia
gdr_cl_41=Habilitar dibujar traza de ruta de tornado

#pestañas del menú de herramientas
gdr_server=servidor
gdr_main=principal
gdr_advanced=Avanzado
gdr_autospawn=Aparición automática
gdr_nc=DNC

gdr_server_hud=Hud del servidor
gdr_addons=complementos
gdr_server_graphics=Gráficos de servidor
gdr_server_hud=Hud del servidor
gdr_volume=Volumen
gdr_advanced_graphics=Gráficos avanzados
gdr_graphics=Gráficos
gdr_hud=Hud
gdr_heatsystem=Sistema de calor (Beta)


#hud

gdr_hud_air_temperature=Temperatura del aire: 
gdr_hud_body_temperature=Temperatura corporal: 
gdr_hud_body_oxygen=Oxígeno Corporal: 
gdr_hud_humidity=Humedad: 

gdr_hud_wind_speed=Velocidad del viento: 
gdr_hud_local_wind_speed=Velocidad local del viento: 
gdr_hud_wind_drection=Dirección del viento: 
gdr_hud_precipitation=Current Precipitation: 
gdr_hud_wet_bulve_temperature=Temperatura de vulva humeda: 
gdr_hud_dewpoint=Punto de rocio: 
gdr_hud_windchill=Wind Chill: 
gdr_hud_heatindex=Calor Index: 
gdr_hud_airflow=Fujo de aire: 
gdr_hud_latentheat=Latent Heat: 
gdr_hud_clouddensity=Densidad de nubes: 
gdr_hud_terraintype=Tipo De Terreno: 
gdr_hud_incomingRadiation=Radiación entrante: 