#настройки св
gdr_d1=Варианты урона, связанные с ветром/торнадо/водой:
gdr_d2=Включить урон, связанный с водой
gdr_d3=Включить урон, связанный с торнадо
gdr_d4=Включить урон, связанный с ветром
gdr_d5=tvirus Параметры:
gdr_d6=Сила зомби
gdr_d7=Зомби NMRIH
gdr_d8=Не связывайтесь с этими настройками, если вы не знаете, что делаете.
gdr_d9=Дополнительные параметры:
gdr_d10=Параметры симуляции (изменить качество симуляции):
gdr_d11=Качество моделирования торнадо
gdr_d12=Качество имитации землетрясения
gdr_d13=Качество имитации воды
gdr_d14=Качество имитации ветра
gdr_d15=Параметры ветра:
gdr_d16=Включить физический ветер
gdr_d17=Включить последующее повреждение Ветром без столкновений
gdr_d18=Включить постповреждение Ветром без столкновения basetimeout
gdr_d19=Включить последующее повреждение Ветром без столкновений с базовым временем
gdr_d20=Включить уменьшение массы после повреждения ветром
gdr_d21=Параметры землетрясения:
gdr_d22=Включить группу столкновений для изменения землетрясения
gdr_d23=Параметры вулкана/луны/астероида:
gdr_d24=Включить изменение климата вулкана / луны / астероида (может вызвать задержку)
gdr_d25=Увеличение давления вулкана/оползня
gdr_d26=Уменьшение давления вулкана/оползня
gdr_d27=Параметры погоды:
gdr_d28=Включить свойства урона от Кислотного дождя (может вызвать задержку)
gdr_d29=Параметры воды/лавы и наводнения/цунами:
gdr_d30=минимальный уровень затопления
gdr_d31=максимальный уровень затопления
gdr_d32=начальный уровень цунами
gdr_d33=Цунами на среднем уровне
gdr_d34=Конечный уровень цунами
gdr_d35=скорость цунами
gdr_d36=Параметры торнадо:
gdr_d37=Включить пользовательскую скорость торнадо
gdr_d38=Скорость торнадо
gdr_d39=Мин. время жизни торнадо
gdr_d40=Максимальное время жизни торнадо
gdr_d41=Урон торнадо
gdr_d42=Графика главного сервера:
gdr_d43=Включить атмосферу
gdr_d44=Включить эффект GFX
gdr_d45=Включить эффект тумана
gdr_d46=Параметры предотвращения столкновений:
gdr_d47=PD NC BT: Post Damage No Collide Base Time\n\nCPPPS: Коллизии на опору в секунду\n\nCAPS: Среднее коллизии в секунду
gdr_d48=Макс. CPPPS
gdr_d49=Макс. PD NC BT
gdr_d50=Макс. CAPS (с)
gdr_d51=Параметры защиты от задержек:
gdr_d52=Режим антилаг (не работает)
gdr_d53=Включить антилаг
gdr_d54=Параметры автопорождения:
gdr_d55=Время появления автоспауна
gdr_d56=Время удаления автоспауна
gdr_d57=Шанс автоспауна
gdr_d58=Параметры коробки автоспауна:
gdr_d59=Отключить торнадо на карте
gdr_d60=Включить сообщения чата
gdr_d61=Включить автоспаун
gdr_d62=Параметры температуры тела:
gdr_d63=Включить температуру тела
gdr_d64=Включить дыхание по температуре тела
gdr_d65=Включить повреждение, связанное с температурой тела
gdr_d66=Включить изменение скорости игрока при температуре тела
gdr_d67=Включить изменение значения температуры тела
gdr_d68=скорость ходьбы игрока по умолчанию
gdr_d69=Скорость спринта игрока по умолчанию
gdr_d70=Параметры кислорода в организме:
gdr_d71=Включить кислород для тела
gdr_d72=Включить урон, связанный с кислородом тела
gdr_d73=Включить урон, связанный с кислородом тела
gdr_d74=DNC: Цикл дня и ночи
gdr_d75=Параметры DNC:
gdr_d76=Включить DNC
gdr_d77=DNC приостановлено
gdr_d78=DNC в реальном времени
gdr_d79=DNC Включить Создать light_environment
gdr_d80=длина дня
gdr_d81=Длина ночи
gdr_d82=Размер Луны
gdr_d83=Параметры космической постройки:
gdr_d84=Включить совместимость космической сборки
gdr_d85=Параметры Stormfox:
gdr_d86=Включить совместимость со Stormfox
gdr_d87=S37K Параметры границ карты:
gdr_d88=Включить границы карты S37K

#настройки кл
gdr_dcl_1=Дополнительные параметры графики:
gdr_dcl_2=Качество воды
gdr_dcl_3=Качество шейдера воды
gdr_dcl_4=Качество лавы
gdr_dcl_5=Качество тумана
gdr_dcl_6=Раздел, посвященный доплеровскому радару.\nИспользуйте с осторожностью.
gdr_dcl_7=разрешение
gdr_dcl_8=монохромный режим
gdr_dcl_9=Максимальное расстояние рендеринга
gdr_dcl_10=Частота обновления (Гц)
gdr_dcl_11=Частота обновления (Гц)
gdr_dcl_12=Параметры графики.
gdr_dcl_13=GP: Частицы земли\n\nWP:Частицы погоды\n\nSP: Частицы экрана
gdr_dcl_14=Включить экспериментальную перерисовку
gdr_dcl_15=Включить встряхивание экрана
gdr_dcl_16=Включить эффекты опускания потолка Draw
gdr_dcl_17=Включить GP
gdr_dcl_18=Включить WP
gdr_dcl_19=Включить SP
gdr_dcl_20=Включить ручной SP
gdr_dcl_21=Макс. SP
gdr_dcl_22=Параметры интерфейса:
gdr_dcl_23=1: экран тела\n\n2: экран давления\n\n3: экран землетрясения\n\n4: экран SpaceBuild
gdr_dcl_24=Включить Худ
gdr_dcl_25=Включить эффекты экрана температуры тела
gdr_dcl_26=Включить температуру тела при рвоте
gdr_dcl_27=Включить чихание температуры тела
gdr_dcl_28=Включить эффекты подводного экрана
gdr_dcl_29=Включить эффекты экрана UnderLava
gdr_dcl_30=Тип интерфейса
gdr_dcl_31=HUD дисплей ветра
gdr_dcl_32=Отображение температуры HUD
gdr_dcl_33=Параметры звука:
gdr_dcl_34=Громкость слабого ветра
gdr_dcl_35=Умеренная громкость ветра
gdr_dcl_36=Громкость сильного ветра
gdr_dcl_37=громкость звуковой волны
gdr_dcl_38=Параметры аудио HUD:
gdr_dcl_39=громкость очага HUD
gdr_dcl_40=Громкость предупреждения HUD
gdr_dcl_41=Включить трассировку «Нарисовать путь торнадо»

#вкладки toolmenu
gdr_dserver=сервер
gdr_dmain=основной
gdr_dadvanced=продвинутый
gdr_dautospawn=автоспаун
gdr_dnc=DNC

gdr_dserver_hud=Интерфейс сервера
gdr_daddons=дополнения
gdr_dserver_graphics=серверная графика
gdr_dserver_hud=интерфейс сервера
gdr_dvolume=громкость
gdr_dadvanced_graphics=Расширенная графика
gdr_dgraphics=Графика
gdr_dhud=Худ

#худ

gdr_dhud_air_temperature=Температура воздуха: 
gdr_dhud_body_temperature=Температура тела: 
gdr_dhud_body_oxygen=Кислород для тела: 
gdr_dhud_humidity=Влажность: 

gdr_dhud_wind_speed=Скорость ветра: 
gdr_dhud_local_wind_speed=Местная скорость ветра: 
gdr_dhud_wind_drection=Направление ветра: 