#настройки св
gdr_1=Варианты урона, связанные с ветром/торнадо/водой:
gdr_2=Включить урон, связанный с водой
gdr_3=Включить урон, связанный с торнадо
gdr_4=Включить урон, связанный с ветром
gdr_5=tvirus Параметры:
gdr_6=Сила зомби
gdr_7=Зомби NMRIH
gdr_8=Не связывайтесь с этими настройками, если вы не знаете, что делаете.
gdr_9=Дополнительные параметры:
gdr_10=Параметры симуляции (изменить качество симуляции):
gdr_11=Качество моделирования торнадо
gdr_12=Качество имитации землетрясения
gdr_13=Качество имитации воды
gdr_14=Качество имитации ветра
gdr_15=Параметры ветра:
gdr_16=Включить физический ветер
gdr_17=Включить последующее повреждение Ветром без столкновений
gdr_18=Включить постповреждение Ветром без столкновения basetimeout
gdr_19=Включить последующее повреждение Ветром без столкновений с базовым временем
gdr_20=Включить уменьшение массы после повреждения ветром
gdr_21=Параметры землетрясения:
gdr_22=Включить группу столкновений для изменения землетрясения
gdr_23=Параметры вулкана/луны/астероида:
gdr_24=Включить изменение климата вулкана / луны / астероида (может вызвать задержку)
gdr_25=Увеличение давления вулкана/оползня
gdr_26=Уменьшение давления вулкана/оползня
gdr_27=Параметры погоды:
gdr_28=Включить свойства урона от Кислотного дождя (может вызвать задержку)
gdr_29=Параметры воды/лавы и наводнения/цунами:
gdr_30=минимальный уровень затопления
gdr_31=максимальный уровень затопления
gdr_32=начальный уровень цунами
gdr_33=Цунами на среднем уровне
gdr_34=Конечный уровень цунами
gdr_35=скорость цунами
gdr_36=Параметры торнадо:
gdr_37=Включить пользовательскую скорость торнадо
gdr_38=Скорость торнадо
gdr_39=Мин. время жизни торнадо
gdr_40=Максимальное время жизни торнадо
gdr_41=Урон торнадо
gdr_42=Графика главного сервера:
gdr_43=Включить атмосферу
gdr_44=Включить эффект GFX
gdr_45=Включить эффект тумана
gdr_46=Параметры предотвращения столкновений:
gdr_47=PD NC BT: Post Damage No Collide Base Time\n\nCPPPS: Коллизии на опору в секунду\n\nCAPS: Среднее коллизии в секунду
gdr_48=Макс. CPPPS
gdr_49=Макс. PD NC BT
gdr_50=Макс. CAPS (с)
gdr_51=Параметры защиты от задержек:
gdr_52=Режим антилаг (не работает)
gdr_53=Включить антилаг
gdr_54=Параметры автопорождения:
gdr_55=Время появления автоспауна
gdr_56=Время удаления автоспауна
gdr_57=Шанс автоспауна
gdr_58=Параметры коробки автоспауна:
gdr_59=Отключить торнадо на карте
gdr_60=Включить сообщения чата
gdr_61=Включить автоспаун
gdr_62=Параметры температуры тела:
gdr_63=Включить температуру тела
gdr_64=Включить дыхание по температуре тела
gdr_65=Включить повреждение, связанное с температурой тела
gdr_66=Включить изменение скорости игрока при температуре тела
gdr_67=Включить изменение значения температуры тела
gdr_68=скорость ходьбы игрока по умолчанию
gdr_69=Скорость спринта игрока по умолчанию
gdr_70=Параметры кислорода в организме:
gdr_71=Включить кислород для тела
gdr_72=Включить урон, связанный с кислородом тела
gdr_73=Включить урон, связанный с кислородом тела
gdr_74=DNC: Цикл дня и ночи
gdr_75=Параметры DNC:
gdr_76=Включить DNC
gdr_77=DNC приостановлено
gdr_78=DNC в реальном времени
gdr_79=DNC Включить Создать light_environment
gdr_80=длина дня
gdr_81=Длина ночи
gdr_82=Размер Луны
gdr_83=Параметры космической постройки:
gdr_84=Включить совместимость космической сборки
gdr_85=Параметры Stormfox:
gdr_86=Включить совместимость со Stormfox
gdr_87=S37K Параметры границ карты:
gdr_88=Включить границы карты S37K

#настройки кл
gdr_cl_1=Дополнительные параметры графики:
gdr_cl_2=Качество воды
gdr_cl_3=Качество шейдера воды
gdr_cl_4=Качество лавы
gdr_cl_5=Качество тумана
gdr_cl_6=Раздел, посвященный доплеровскому радару.\nИспользуйте с осторожностью.
gdr_cl_7=разрешение
gdr_cl_8=монохромный режим
gdr_cl_9=Максимальное расстояние рендеринга
gdr_cl_10=Частота обновления (Гц)
gdr_cl_11=Частота обновления (Гц)
gdr_cl_12=Параметры графики.
gdr_cl_13=GP: Частицы земли\n\nWP:Частицы погоды\n\nSP: Частицы экрана
gdr_cl_14=Включить экспериментальную перерисовку
gdr_cl_15=Включить встряхивание экрана
gdr_cl_16=Включить эффекты опускания потолка Draw
gdr_cl_17=Включить GP
gdr_cl_18=Включить WP
gdr_cl_19=Включить SP
gdr_cl_20=Включить ручной SP
gdr_cl_21=Макс. SP
gdr_cl_22=Параметры интерфейса:
gdr_cl_23=1: экран тела\n\n2: экран давления\n\n3: экран землетрясения\n\n4: экран SpaceBuild
gdr_cl_24=Включить Худ
gdr_cl_25=Включить эффекты экрана температуры тела
gdr_cl_26=Включить температуру тела при рвоте
gdr_cl_27=Включить чихание температуры тела
gdr_cl_28=Включить эффекты подводного экрана
gdr_cl_29=Включить эффекты экрана UnderLava
gdr_cl_30=Тип интерфейса
gdr_cl_31=HUD дисплей ветра
gdr_cl_32=Отображение температуры HUD
gdr_cl_33=Параметры звука:
gdr_cl_34=Громкость слабого ветра
gdr_cl_35=Умеренная громкость ветра
gdr_cl_36=Громкость сильного ветра
gdr_cl_37=громкость звуковой волны
gdr_cl_38=Параметры аудио HUD:
gdr_cl_39=громкость очага HUD
gdr_cl_40=Громкость предупреждения HUD
gdr_cl_41=Включить трассировку «Нарисовать путь торнадо»

#вкладки toolmenu
gdr_server=сервер
gdr_main=основной
gdr_advanced=продвинутый
gdr_autospawn=автоспаун
gdr_nc=DNC

gdr_server_hud=Интерфейс сервера
gdr_addons=дополнения
gdr_server_graphics=серверная графика
gdr_server_hud=интерфейс сервера
gdr_volume=громкость
gdr_advanced_graphics=Расширенная графика
gdr_graphics=Графика
gdr_hud=Худ

#худ

gdr_hud_air_temperature=Температура воздуха: 
gdr_hud_body_temperature=Температура тела: 
gdr_hud_body_oxygen=Кислород для тела: 
gdr_hud_humidity=Влажность: 

gdr_hud_wind_speed=Скорость ветра: 
gdr_hud_local_wind_speed=Местная скорость ветра: 
gdr_hud_wind_drection=Направление ветра: 