#settings sv
gdr_d1=Wind/Tornado/Water Related Damage Options:
gdr_d2=Enable Water Related Damage
gdr_d3=Enable Tornado Related Damage
gdr_d4=Enable Wind Related Damage
gdr_d5=tvirus Options:
gdr_d6=Zombie Strength
gdr_d7=NMRIH Zombies
gdr_d8=Dont mess with these settings unless you know what you re doing.
gdr_d9=Advanced Options:
gdr_d10=Simulation Option (Change the quality of simulation):
gdr_d11=Tornado Simulation Quality
gdr_d12=Earthquake Simulation Quality
gdr_d13=Water Simulation Quality
gdr_d14=Wind Simulation Quality
gdr_d15=Wind Options:
gdr_d16=Enable Wind physical
gdr_d17=Enable Wind postdamage no collide
gdr_d18=Enable Wind postdamage no collide basetimeout
gdr_d19=Enable Wind postdamage no collide basetime spread
gdr_d20=Enable Wind postdamage reducemass
gdr_d21=Eathquake Options:
gdr_d22=Enable earthquake change collision group
gdr_d23=Volcano/Moon/Asteroid Options:
gdr_d24=Enable volcano/moon/asteroid climate change (Can cause lag)
gdr_d25=Volcano/Landslide Presure Increase
gdr_d26=Volcano/Landslide Presure Decrease
gdr_d27=Weather Options: 
gdr_d28=Enable Acid Rain damage props (Can cause lag)
gdr_d28.1=Enable Acid Rain damage npcs(Can cause lag)
gdr_d29=Water/Lava and Flood/Tsunami Options:
gdr_d30=min flood level
gdr_d31=max flood level
gdr_d32=Tsunami start level
gdr_d33=Tsunami middel level
gdr_d34=Tsunami end level
gdr_d35=Tsunami speed
gdr_d36=Tornado Options:
gdr_d37=Enable Custom Tornado Speed
gdr_d38=Tornado Speed
gdr_d39=Tornado Lifetime min
gdr_d40=Tornado Lifetime max
gdr_d41=Tornado Damage
gdr_d42=Main Server Graphics:
gdr_d43=Enable Atmosphere
gdr_d44=Enable GFX effect
gdr_d45=Enable Fog Effect
gdr_d46=Antilag Collision Options:
gdr_d47=PD NC BT: Post Damage No Collide Base Time\n\nCPPPS: Collisions Per Prop Per Second\n\nCAPS:Collisions Average Per Second
gdr_d48=Max CPPPS
gdr_d49=Max PD NC BT
gdr_d50=Max CAPS (s)
gdr_d51=Antilag Options:
gdr_d52=Antilag Mode (No Work)
gdr_d53=Enable Antilag
gdr_d54=Autospawn Options:
gdr_d55=Autospawn Spawn Time
gdr_d56=Autospawn Remove Time
gdr_d57=Autospawn Chance
gdr_d58=Autospawn Box Options:
gdr_d59=Disable Map Tornadoes
gdr_d60=Enable Chat Messages
gdr_d61=Enable Autospawn
gdr_d62=Body Temperature Options:
gdr_d63=Enable Body Temperature
gdr_d64=Enable Body Temperature Breathing
gdr_d65=Enable Body Temperature Related Damage
gdr_d65.1=Enable NPC Temperature
gdr_d66=Enable Body Temperature Change Player Speed
gdr_d67=Enable Change Value of Body Temperature
gdr_d68=Default player walk speed
gdr_d69=Default player sprint speed
gdr_d70=Body Oxygen Options:
gdr_d71=Enable Body Oxygen
gdr_d71.1=Enable NPC Oxygen
gdr_d72=Enable Body Oxygen Related Damage
gdr_d73=Enable Body Oxygen Related Damage
gdr_d74=DNC: Day And Night Cycle
gdr_d75=DNC Options:
gdr_d76=DNC Enable
gdr_d77=DNC Paused
gdr_d78=DNC Realtime
gdr_d79=DNC Enable Create light_environment
gdr_d80=Length Day
gdr_d81=Length Night
gdr_d82=Moon Size
gdr_d83=Spacebuild Options:
gdr_d84=Enable Spacebuild Compatibility
gdr_d85=Stormfox Options:
gdr_d86=Enable Stormfox Compatibility
gdr_d87=Enable Heat System grid
gdr_d88=Enable Heat System

#settings cl
gdr_dcl_1=Advanced Graphics Options:
gdr_dcl_2=Water Quality
gdr_dcl_3=Water Shader Quality
gdr_dcl_4=Lava Quality
gdr_dcl_5=Fog Quality
gdr_dcl_6=Section dedicated to Doppler Radar.\nUse with caution.
gdr_dcl_7=Resolution
gdr_dcl_8=Monochromatic Mode
gdr_dcl_9=Max Render Distance
gdr_dcl_10=Refresh Rate (Hz)
gdr_dcl_11=Update  Rate (Hz)
gdr_dcl_12=Graphics Options.
gdr_dcl_13=GP: Ground Particles\n\nWP:Weather Particles\n\nSP: Screen Particles
gdr_dcl_14=Enable Experimental Overdraw
gdr_dcl_15=Enable Shake Screen
gdr_dcl_16=Enable Draw ceiling drop effects
gdr_dcl_17=Enable GP
gdr_dcl_18=Enable WP
gdr_dcl_19=Enable SP
gdr_dcl_20=Enable Manual SP
gdr_dcl_21=Max SP
gdr_dcl_22=Hud Options:
gdr_dcl_23=1: body hud\n\n2: pressure hud\n\n3: earthquake hud\n\n4: SpaceBuild hud\n\n5: Heat System Hud
gdr_dcl_24=Enable Hud
gdr_dcl_25=Enable Body Temperature Screen Effects
gdr_dcl_26=Enable Body Temperature Vomit
gdr_dcl_27=Enable Body Temperature Sneeze
gdr_dcl_28=Enable Underwater Screen Effects
gdr_dcl_29=Enable UnderLava Screen Effects
gdr_dcl_30=Hud Type
gdr_dcl_31=Hud Wind Display
gdr_dcl_32=Hud Temperature Display
gdr_dcl_33=Audio Options:
gdr_dcl_34=Light Wind Volume
gdr_dcl_35=Moderate Wind Volume
gdr_dcl_36=Heavy Wind Volume
gdr_dcl_37=SoundWave Volume
gdr_dcl_38=Hud Audio Options:
gdr_dcl_39=hud Hearth Volume
gdr_dcl_40=hud Warning Volume
gdr_dcl_41=Enable Draw Tornado Path trace

#toolmenu tabs
gdr_dserver=server
gdr_dmain=main
gdr_dadvanced=Advanced
gdr_dautospawn=Autospawn
gdr_dnc=DNC

gdr_dserver_hud=Server Hud
gdr_daddons=addons
gdr_dserver_graphics=Server Graphics
gdr_dserver_hud=Server hud
gdr_dvolume=Volume
gdr_dadvanced_graphics=Advanced Graphics
gdr_dgraphics=Graphics
gdr_dhud=Hud
gdr_dheatsystem=Heat System (Beta)

#hud

gdr_dhud_air_temperature=Air Temperature: 
gdr_dhud_body_temperature=Body Temperature: 
gdr_dhud_body_oxygen=Body Oxygen: 
gdr_dhud_humidity=Humidity: 

gdr_dhud_wind_speed=Wind Speed: 
gdr_dhud_local_wind_speed=Local Wind Speed: 
gdr_dhud_wind_drection=Wind Direction: 
gdr_dhud_precipitation=Current Precipitation:  
gdr_dhud_wet_bulve_temperature=Air Wet Temperature: 
gdr_dhud_dewpoint=Dew Point: 
gdr_dhud_windchill=Wind Chill: 
gdr_dhud_heatindex=Heat Index: 
gdr_dhud_airflow=Air Flow: 
gdr_dhud_latentheat=Latent Heat: 
gdr_dhud_clouddensity=Cloud Density: 
gdr_dhud_terraintype=Terrain Type:
gdr_dhud_incomingRadiation=Radiación entrante: 

