#settings sv
gdr_1=Wind/Tornado/Water Related Damage Options:
gdr_2=Enable Water Related Damage
gdr_3=Enable Tornado Related Damage
gdr_4=Enable Wind Related Damage
gdr_5=tvirus Options:
gdr_6=Zombie Strength
gdr_7=NMRIH Zombies
gdr_8=Dont mess with these settings unless you know what you re doing.
gdr_9=Advanced Options:
gdr_10=Simulation Option (Change the quality of simulation):
gdr_11=Tornado Simulation Quality
gdr_12=Earthquake Simulation Quality
gdr_13=Water Simulation Quality
gdr_14=Wind Simulation Quality
gdr_15=Wind Options:
gdr_16=Enable Wind physical
gdr_17=Enable Wind postdamage no collide
gdr_18=Enable Wind postdamage no collide basetimeout
gdr_19=Enable Wind postdamage no collide basetime spread
gdr_20=Enable Wind postdamage reducemass
gdr_21=Eathquake Options:
gdr_22=Enable earthquake change collision group
gdr_23=Volcano/Moon/Asteroid Options:
gdr_24=Enable volcano/moon/asteroid climate change (Can cause lag)
gdr_25=Volcano/Landslide Presure Increase
gdr_26=Volcano/Landslide Presure Decrease
gdr_27=Weather Options: 
gdr_28=Enable Acid Rain damage props (Can cause lag)
gdr_28.1=Enable Acid Rain damage npcs(Can cause lag)
gdr_29=Water/Lava and Flood/Tsunami Options:
gdr_30=min flood level
gdr_31=max flood level
gdr_32=Tsunami start level
gdr_33=Tsunami middel level
gdr_34=Tsunami end level
gdr_35=Tsunami speed
gdr_36=Tornado Options:
gdr_37=Enable Custom Tornado Speed
gdr_38=Tornado Speed
gdr_39=Tornado Lifetime min
gdr_40=Tornado Lifetime max
gdr_41=Tornado Damage
gdr_42=Main Server Graphics:
gdr_43=Enable Atmosphere
gdr_44=Enable GFX effect
gdr_45=Enable Fog Effect
gdr_46=Antilag Collision Options:
gdr_47=PD NC BT: Post Damage No Collide Base Time\n\nCPPPS: Collisions Per Prop Per Second\n\nCAPS:Collisions Average Per Second
gdr_48=Max CPPPS
gdr_49=Max PD NC BT
gdr_50=Max CAPS (s)
gdr_51=Antilag Options:
gdr_52=Antilag Mode (No Work)
gdr_53=Enable Antilag
gdr_54=Autospawn Options:
gdr_55=Autospawn Spawn Time
gdr_56=Autospawn Remove Time
gdr_57=Autospawn Chance
gdr_58=Autospawn Box Options:
gdr_59=Disable Map Tornadoes
gdr_60=Enable Chat Messages
gdr_61=Enable Autospawn
gdr_62=Body Temperature Options:
gdr_63=Enable Body Temperature
gdr_64=Enable Body Temperature Breathing
gdr_65=Enable Body Temperature Related Damage
gdr_65.1=Enable NPC Temperature
gdr_66=Enable Body Temperature Change Player Speed
gdr_67=Enable Change Value of Body Temperature
gdr_68=Default player walk speed
gdr_69=Default player sprint speed
gdr_70=Body Oxygen Options:
gdr_71=Enable Body Oxygen
gdr_71.1=Enable NPC Oxygen
gdr_72=Enable Body Oxygen Related Damage
gdr_73=Enable Body Oxygen Related Damage
gdr_74=DNC: Day And Night Cycle
gdr_75=DNC Options:
gdr_76=DNC Enable
gdr_77=DNC Paused
gdr_78=DNC Realtime
gdr_79=DNC Enable Create light_environment
gdr_80=Length Day
gdr_81=Length Night
gdr_82=Moon Size
gdr_83=Spacebuild Options:
gdr_84=Enable Spacebuild Compatibility
gdr_85=Stormfox Options:
gdr_86=Enable Stormfox Compatibility
gdr_87=Enable Heat System grid
gdr_88=Enable Heat System

#settings cl
gdr_cl_1=Advanced Graphics Options:
gdr_cl_2=Water Quality
gdr_cl_3=Water Shader Quality
gdr_cl_4=Lava Quality
gdr_cl_5=Fog Quality
gdr_cl_6=Section dedicated to Doppler Radar.\nUse with caution.
gdr_cl_7=Resolution
gdr_cl_8=Monochromatic Mode
gdr_cl_9=Max Render Distance
gdr_cl_10=Refresh Rate (Hz)
gdr_cl_11=Update  Rate (Hz)
gdr_cl_12=Graphics Options.
gdr_cl_13=GP: Ground Particles\n\nWP:Weather Particles\n\nSP: Screen Particles
gdr_cl_14=Enable Experimental Overdraw
gdr_cl_15=Enable Shake Screen
gdr_cl_16=Enable Draw ceiling drop effects
gdr_cl_17=Enable GP
gdr_cl_18=Enable WP
gdr_cl_19=Enable SP
gdr_cl_20=Enable Manual SP
gdr_cl_21=Max SP
gdr_cl_22=Hud Options:
gdr_cl_23=1: body hud\n\n2: pressure hud\n\n3: earthquake hud\n\n4: SpaceBuild hud\n\n5: Heat System Hud
gdr_cl_24=Enable Hud
gdr_cl_25=Enable Body Temperature Screen Effects
gdr_cl_26=Enable Body Temperature Vomit
gdr_cl_27=Enable Body Temperature Sneeze
gdr_cl_28=Enable Underwater Screen Effects
gdr_cl_29=Enable UnderLava Screen Effects
gdr_cl_30=Hud Type
gdr_cl_31=Hud Wind Display
gdr_cl_32=Hud Temperature Display
gdr_cl_33=Audio Options:
gdr_cl_34=Light Wind Volume
gdr_cl_35=Moderate Wind Volume
gdr_cl_36=Heavy Wind Volume
gdr_cl_37=SoundWave Volume
gdr_cl_38=Hud Audio Options:
gdr_cl_39=hud Hearth Volume
gdr_cl_40=hud Warning Volume
gdr_cl_41=Enable Draw Tornado Path trace

#toolmenu tabs
gdr_server=server
gdr_main=main
gdr_advanced=Advanced
gdr_autospawn=Autospawn
gdr_nc=DNC

gdr_server_hud=Server Hud
gdr_addons=addons
gdr_server_graphics=Server Graphics
gdr_server_hud=Server hud
gdr_volume=Volume
gdr_advanced_graphics=Advanced Graphics
gdr_graphics=Graphics
gdr_hud=Hud
gdr_heatsystem=Heat System (Beta)

#hud

gdr_hud_air_temperature=Air Temperature: 
gdr_hud_body_temperature=Body Temperature: 
gdr_hud_body_oxygen=Body Oxygen: 
gdr_hud_humidity=Humidity: 

gdr_hud_wind_speed=Wind Speed: 
gdr_hud_local_wind_speed=Local Wind Speed: 
gdr_hud_wind_drection=Wind Direction: 
gdr_hud_precipitation=Current Precipitation:  
gdr_hud_wet_bulve_temperature=Air Wet Temperature: 
gdr_hud_dewpoint=Dew Point: 
gdr_hud_windchill=Wind Chill: 
gdr_hud_heatindex=Heat Index: 
gdr_hud_airflow=Air Flow: 
gdr_hud_latentheat=Latent Heat: 
gdr_hud_clouddensity=Cloud Density: 
gdr_hud_terraintype=Terrain Type:
gdr_hud_incomingRadiation=Radiación entrante: 

